### ISSUE TITLE
Now Playing song info not updated after playing song with missing info

### ISSUE THREAD

**Issue by denbeigh2000** [dhowden/tchaik#36]
Steps to reproduce:
 1. Play a song with fully populated info
 2. Play a song with missing info

When playing the song with missing info, only the artwork and name of the song changes

![tchaik-timestop-1](https://cloud.githubusercontent.com/assets/1646744/7643411/c6a5d582-fadc-11e4-95f2-b91ab1e96099.png)

Until I switched to a song with fully populated info, the time was fixed at 1:28, and the artist name didn't change

**Comment by dhowden** [comment]
Well spotted! Fixed in ee4fdc820.
